### ISSUE TITLE
代码有错误

### ISSUE THREAD

**Issue by erhutime** [Kennytian/LagouApp#1]
排除自身环境问题，run-android之后，也构建成功，出现错误，提示：can not variable:items,其他提示信息无用，还没有排查到原因。

**Comment by Kennytian** [comment]
就job-data.js和discover-data.js两个文件里有items，我这的环境是 react-native 0.21.0,  react-native-cli: 0.1.10,   node v4.4.0，没有报你说的这个错。 

要不你把你的环境，你的详细错误信息发我看看。

**Comment by febobo** [comment]
在job-data.js和discover-data.js 的第一行加上一句let items; 可解决错误

**Comment by febobo** [comment]
建议文件都放一个目录里

**Comment by erhutime** [comment]
不好意思，刚看到，晚点验证一下解决思路，谢谢！

**Comment by sherylynn** [comment]
加了let items后能进了,但是点击tab后不能切换,ios和android下皆是如此

**Comment by erhutime** [comment]
不好意思，我来反映几点问题：1--首先页面特别卡顿，在点击我的时候，会提示警告，点击进入发现二级页面，出现错误 2--个人认为没有做到适配，我在不同的手机上，运行得到不同的效果 3--点击下面的tab切换页面，卡顿的更厉害
目前为止，发现这样的问题，不过，也感谢楼主，提供了学习的机会，让我搞明白了几个之前一直糊涂的知识点，感谢。

**Comment by XiaoxiaoJoker** [comment]
安卓版：“我的”那里StyleSheet->backgroundImage-->resizeMode报异常，提示这个是不支持的属性

**Comment by Kennytian** [comment]
Image有resizeMode属性啊，你估计是react native 0.21的bug，哈哈！

**Comment by Kennytian** [comment]
我修复了这个问题，快来一起学吧！
