### ISSUE TITLE
下面那个tabbar如何隐藏

### ISSUE THREAD

**Issue by KanNgai** [Kennytian/LagouApp#2]
点任何链接进入二级页面后，下面的TAB栏应该隐藏比较合理，如何实现呢。像手机淘宝、微信、支付宝等跟这布局类似，进入具体内容后那栏都会消失。

**Comment by Kennytian** [comment]
很遗憾，我研究了一上午，没有成功，如果你知道怎么处理，请pull requests进来，谢谢！

**Comment by KanNgai** [comment]
之前我看过两种解决方案，一种说是Navigator包TabBar，但我没试成功，而且也没人这么干。另一种是改源码，如下：

> 找到RCTNavigator.m，在

`(void)navigationController:(UINavigationController )navigationController willShowViewController:(__unused UIViewController *)viewController animated:(__unused BOOL)animated`

> 方法一开始的地方插入语句：

`RCTWrapperViewController * thisController = (RCTWrapperViewController *)viewController;
if (navigationController.viewControllers.count > 1) {
  thisController.tabBarController.tabBar.hidden = YES;
} else {
  thisController.tabBarController.tabBar.hidden = NO;
}`

第二种办法，试了倒是可以，但缺点是要改源码，一但升级react native版本什么的就容易覆盖什么的，另外有人说这方法有问题，具体怎么说的没搞很清楚，大概意思，说在二级页面里划一下页面显示出首面后，再放开，这时下面这栏就跑出来了，具体没试过。

**Comment by Kennytian** [comment]
谢谢你的分享，我稍后试试！

**Comment by Kennytian** [comment]
我修复了这个问题，快来一起学吧！

**Comment by zengxiang** [comment]
@Kennytian 

就可以影藏了 那个页面要隐藏就写在那个页面里
<img width="244" alt="13" src="https://cloud.githubusercontent.com/assets/8578988/18274247/143dc626-7474-11e6-8afc-a72b830be652.png">
