### ISSUE TITLE
xcode7编译底部点击没有反应

### ISSUE THREAD

**Issue by addcn** [Kennytian/LagouApp#4]

**Comment by hanhailong** [comment]
同遇到这个问题了，不管是android还是ios，点击下面的tab都不起作用

**Comment by grape1977** [comment]
问题一样

**Comment by grape1977** [comment]
shouldComponentUpdate func in framepage.js should not return false.  guys can try change this ,then everything is OK!

**Comment by yaderick** [comment]
the same as same

**Comment by hanhailong** [comment]
解决了，楼主埋了大坑给我们！哈哈！

改成true 或者去掉这个返回值就好了

**Comment by Kennytian** [comment]
我修复了这个问题，快来一起学吧！
